-- Backfill real poster art onto catalog rows seeded before posters were
-- imported. Idempotent: only fills rows whose image is still NULL, so it is
-- safe whether the table is empty, partially seeded, or already correct.
-- Each base title also covers its edition SKUs ("Title (4K UHD Steelbook)", ...).

UPDATE deals SET image = '/posters/1917.jpg' WHERE image IS NULL AND (title = '1917' OR title LIKE '1917 (%' ESCAPE '\');
UPDATE deals SET image = '/posters/2001-a-space-odyssey.jpg' WHERE image IS NULL AND (title = '2001: A Space Odyssey' OR title LIKE '2001: A Space Odyssey (%' ESCAPE '\');
UPDATE deals SET image = '/posters/a-quiet-place.jpg' WHERE image IS NULL AND (title = 'A Quiet Place' OR title LIKE 'A Quiet Place (%' ESCAPE '\');
UPDATE deals SET image = '/posters/a-quiet-place-part-ii.jpg' WHERE image IS NULL AND (title = 'A Quiet Place Part II' OR title LIKE 'A Quiet Place Part II (%' ESCAPE '\');
UPDATE deals SET image = '/posters/a-real-pain.jpg' WHERE image IS NULL AND (title = 'A Real Pain' OR title LIKE 'A Real Pain (%' ESCAPE '\');
UPDATE deals SET image = '/posters/aftersun.jpg' WHERE image IS NULL AND (title = 'Aftersun' OR title LIKE 'Aftersun (%' ESCAPE '\');
UPDATE deals SET image = '/posters/air.jpg' WHERE image IS NULL AND (title = 'Air' OR title LIKE 'Air (%' ESCAPE '\');
UPDATE deals SET image = '/posters/alien.jpg' WHERE image IS NULL AND (title = 'Alien' OR title LIKE 'Alien (%' ESCAPE '\');
UPDATE deals SET image = '/posters/aliens.jpg' WHERE image IS NULL AND (title = 'Aliens' OR title LIKE 'Aliens (%' ESCAPE '\');
UPDATE deals SET image = '/posters/american-fiction.jpg' WHERE image IS NULL AND (title = 'American Fiction' OR title LIKE 'American Fiction (%' ESCAPE '\');
UPDATE deals SET image = '/posters/anatomy-of-a-fall.jpg' WHERE image IS NULL AND (title = 'Anatomy of a Fall' OR title LIKE 'Anatomy of a Fall (%' ESCAPE '\');
UPDATE deals SET image = '/posters/annihilation.jpg' WHERE image IS NULL AND (title = 'Annihilation' OR title LIKE 'Annihilation (%' ESCAPE '\');
UPDATE deals SET image = '/posters/anora.jpg' WHERE image IS NULL AND (title = 'Anora' OR title LIKE 'Anora (%' ESCAPE '\');
UPDATE deals SET image = '/posters/apocalypse-now.jpg' WHERE image IS NULL AND (title = 'Apocalypse Now' OR title LIKE 'Apocalypse Now (%' ESCAPE '\');
UPDATE deals SET image = '/posters/arrival.jpg' WHERE image IS NULL AND (title = 'Arrival' OR title LIKE 'Arrival (%' ESCAPE '\');
UPDATE deals SET image = '/posters/asteroid-city.jpg' WHERE image IS NULL AND (title = 'Asteroid City' OR title LIKE 'Asteroid City (%' ESCAPE '\');
UPDATE deals SET image = '/posters/back-to-the-future.jpg' WHERE image IS NULL AND (title = 'Back to the Future' OR title LIKE 'Back to the Future (%' ESCAPE '\');
UPDATE deals SET image = '/posters/barbarian.jpg' WHERE image IS NULL AND (title = 'Barbarian' OR title LIKE 'Barbarian (%' ESCAPE '\');
UPDATE deals SET image = '/posters/beetlejuice-beetlejuice.jpg' WHERE image IS NULL AND (title = 'Beetlejuice Beetlejuice' OR title LIKE 'Beetlejuice Beetlejuice (%' ESCAPE '\');
UPDATE deals SET image = '/posters/blackberry.jpg' WHERE image IS NULL AND (title = 'BlackBerry' OR title LIKE 'BlackBerry (%' ESCAPE '\');
UPDATE deals SET image = '/posters/blade-runner-2049.jpg' WHERE image IS NULL AND (title = 'Blade Runner 2049' OR title LIKE 'Blade Runner 2049 (%' ESCAPE '\');
UPDATE deals SET image = '/posters/booksmart.jpg' WHERE image IS NULL AND (title = 'Booksmart' OR title LIKE 'Booksmart (%' ESCAPE '\');
UPDATE deals SET image = '/posters/bridesmaids.jpg' WHERE image IS NULL AND (title = 'Bridesmaids' OR title LIKE 'Bridesmaids (%' ESCAPE '\');
UPDATE deals SET image = '/posters/casablanca.jpg' WHERE image IS NULL AND (title = 'Casablanca' OR title LIKE 'Casablanca (%' ESCAPE '\');
UPDATE deals SET image = '/posters/casino.jpg' WHERE image IS NULL AND (title = 'Casino' OR title LIKE 'Casino (%' ESCAPE '\');
UPDATE deals SET image = '/posters/children-of-men.jpg' WHERE image IS NULL AND (title = 'Children of Men' OR title LIKE 'Children of Men (%' ESCAPE '\');
UPDATE deals SET image = '/posters/civil-war.jpg' WHERE image IS NULL AND (title = 'Civil War' OR title LIKE 'Civil War (%' ESCAPE '\');
UPDATE deals SET image = '/posters/coco.jpg' WHERE image IS NULL AND (title = 'Coco' OR title LIKE 'Coco (%' ESCAPE '\');
UPDATE deals SET image = '/posters/conclave.jpg' WHERE image IS NULL AND (title = 'Conclave' OR title LIKE 'Conclave (%' ESCAPE '\');
UPDATE deals SET image = '/posters/deadpool-and-wolverine.jpg' WHERE image IS NULL AND (title = 'Deadpool & Wolverine' OR title LIKE 'Deadpool & Wolverine (%' ESCAPE '\');
UPDATE deals SET image = '/posters/decision-to-leave.jpg' WHERE image IS NULL AND (title = 'Decision to Leave' OR title LIKE 'Decision to Leave (%' ESCAPE '\');
UPDATE deals SET image = '/posters/despicable-me-4.jpg' WHERE image IS NULL AND (title = 'Despicable Me 4' OR title LIKE 'Despicable Me 4 (%' ESCAPE '\');
UPDATE deals SET image = '/posters/die-hard.jpg' WHERE image IS NULL AND (title = 'Die Hard' OR title LIKE 'Die Hard (%' ESCAPE '\');
UPDATE deals SET image = '/posters/district-9.jpg' WHERE image IS NULL AND (title = 'District 9' OR title LIKE 'District 9 (%' ESCAPE '\');
UPDATE deals SET image = '/posters/django-unchained.jpg' WHERE image IS NULL AND (title = 'Django Unchained' OR title LIKE 'Django Unchained (%' ESCAPE '\');
UPDATE deals SET image = '/posters/dune.jpg' WHERE image IS NULL AND (title = 'Dune' OR title LIKE 'Dune (%' ESCAPE '\');
UPDATE deals SET image = '/posters/dunkirk.jpg' WHERE image IS NULL AND (title = 'Dunkirk' OR title LIKE 'Dunkirk (%' ESCAPE '\');
UPDATE deals SET image = '/posters/edge-of-tomorrow.jpg' WHERE image IS NULL AND (title = 'Edge of Tomorrow' OR title LIKE 'Edge of Tomorrow (%' ESCAPE '\');
UPDATE deals SET image = '/posters/elemental.jpg' WHERE image IS NULL AND (title = 'Elemental' OR title LIKE 'Elemental (%' ESCAPE '\');
UPDATE deals SET image = '/posters/encanto.jpg' WHERE image IS NULL AND (title = 'Encanto' OR title LIKE 'Encanto (%' ESCAPE '\');
UPDATE deals SET image = '/posters/eternals.jpg' WHERE image IS NULL AND (title = 'Eternals' OR title LIKE 'Eternals (%' ESCAPE '\');
UPDATE deals SET image = '/posters/everything-everywhere-all-at-once.jpg' WHERE image IS NULL AND (title = 'Everything Everywhere All at Once' OR title LIKE 'Everything Everywhere All at Once (%' ESCAPE '\');
UPDATE deals SET image = '/posters/ex-machina.jpg' WHERE image IS NULL AND (title = 'Ex Machina' OR title LIKE 'Ex Machina (%' ESCAPE '\');
UPDATE deals SET image = '/posters/extraction-2.jpg' WHERE image IS NULL AND (title = 'Extraction 2' OR title LIKE 'Extraction 2 (%' ESCAPE '\');
UPDATE deals SET image = '/posters/ferrari.jpg' WHERE image IS NULL AND (title = 'Ferrari' OR title LIKE 'Ferrari (%' ESCAPE '\');
UPDATE deals SET image = '/posters/fight-club.jpg' WHERE image IS NULL AND (title = 'Fight Club' OR title LIKE 'Fight Club (%' ESCAPE '\');
UPDATE deals SET image = '/posters/forrest-gump.jpg' WHERE image IS NULL AND (title = 'Forrest Gump' OR title LIKE 'Forrest Gump (%' ESCAPE '\');
UPDATE deals SET image = '/posters/furiosa-a-mad-max-saga.jpg' WHERE image IS NULL AND (title = 'Furiosa: A Mad Max Saga' OR title LIKE 'Furiosa: A Mad Max Saga (%' ESCAPE '\');
UPDATE deals SET image = '/posters/game-night.jpg' WHERE image IS NULL AND (title = 'Game Night' OR title LIKE 'Game Night (%' ESCAPE '\');
UPDATE deals SET image = '/posters/get-out.jpg' WHERE image IS NULL AND (title = 'Get Out' OR title LIKE 'Get Out (%' ESCAPE '\');
UPDATE deals SET image = '/posters/gladiator.jpg' WHERE image IS NULL AND (title = 'Gladiator' OR title LIKE 'Gladiator (%' ESCAPE '\');
UPDATE deals SET image = '/posters/gladiator-ii.jpg' WHERE image IS NULL AND (title = 'Gladiator II' OR title LIKE 'Gladiator II (%' ESCAPE '\');
UPDATE deals SET image = '/posters/glass-onion.jpg' WHERE image IS NULL AND (title = 'Glass Onion' OR title LIKE 'Glass Onion (%' ESCAPE '\');
UPDATE deals SET image = '/posters/goodfellas.jpg' WHERE image IS NULL AND (title = 'Goodfellas' OR title LIKE 'Goodfellas (%' ESCAPE '\');
UPDATE deals SET image = '/posters/gravity.jpg' WHERE image IS NULL AND (title = 'Gravity' OR title LIKE 'Gravity (%' ESCAPE '\');
UPDATE deals SET image = '/posters/guardians-of-the-galaxy-vol-3.jpg' WHERE image IS NULL AND (title = 'Guardians of the Galaxy Vol. 3' OR title LIKE 'Guardians of the Galaxy Vol. 3 (%' ESCAPE '\');
UPDATE deals SET image = '/posters/heat.jpg' WHERE image IS NULL AND (title = 'Heat' OR title LIKE 'Heat (%' ESCAPE '\');
UPDATE deals SET image = '/posters/hereditary.jpg' WHERE image IS NULL AND (title = 'Hereditary' OR title LIKE 'Hereditary (%' ESCAPE '\');
UPDATE deals SET image = '/posters/how-to-train-your-dragon.jpg' WHERE image IS NULL AND (title = 'How to Train Your Dragon' OR title LIKE 'How to Train Your Dragon (%' ESCAPE '\');
UPDATE deals SET image = '/posters/if.jpg' WHERE image IS NULL AND (title = 'IF' OR title LIKE 'IF (%' ESCAPE '\');
UPDATE deals SET image = '/posters/inception.jpg' WHERE image IS NULL AND (title = 'Inception' OR title LIKE 'Inception (%' ESCAPE '\');
UPDATE deals SET image = '/posters/indiana-jones-and-the-dial-of-destiny.jpg' WHERE image IS NULL AND (title = 'Indiana Jones and the Dial of Destiny' OR title LIKE 'Indiana Jones and the Dial of Destiny (%' ESCAPE '\');
UPDATE deals SET image = '/posters/inglourious-basterds.jpg' WHERE image IS NULL AND (title = 'Inglourious Basterds' OR title LIKE 'Inglourious Basterds (%' ESCAPE '\');
UPDATE deals SET image = '/posters/inside-out.jpg' WHERE image IS NULL AND (title = 'Inside Out' OR title LIKE 'Inside Out (%' ESCAPE '\');
UPDATE deals SET image = '/posters/inside-out-2.jpg' WHERE image IS NULL AND (title = 'Inside Out 2' OR title LIKE 'Inside Out 2 (%' ESCAPE '\');
UPDATE deals SET image = '/posters/interstellar.jpg' WHERE image IS NULL AND (title = 'Interstellar' OR title LIKE 'Interstellar (%' ESCAPE '\');
UPDATE deals SET image = '/posters/it.jpg' WHERE image IS NULL AND (title = 'It' OR title LIKE 'It (%' ESCAPE '\');
UPDATE deals SET image = '/posters/jaws.jpg' WHERE image IS NULL AND (title = 'Jaws' OR title LIKE 'Jaws (%' ESCAPE '\');
UPDATE deals SET image = '/posters/john-wick.jpg' WHERE image IS NULL AND (title = 'John Wick' OR title LIKE 'John Wick (%' ESCAPE '\');
UPDATE deals SET image = '/posters/john-wick-chapter-4.jpg' WHERE image IS NULL AND (title = 'John Wick: Chapter 4' OR title LIKE 'John Wick: Chapter 4 (%' ESCAPE '\');
UPDATE deals SET image = '/posters/jojo-rabbit.jpg' WHERE image IS NULL AND (title = 'Jojo Rabbit' OR title LIKE 'Jojo Rabbit (%' ESCAPE '\');
UPDATE deals SET image = '/posters/joker.jpg' WHERE image IS NULL AND (title = 'Joker' OR title LIKE 'Joker (%' ESCAPE '\');
UPDATE deals SET image = '/posters/joker-folie-deux.jpg' WHERE image IS NULL AND (title = 'Joker: Folie à Deux' OR title LIKE 'Joker: Folie à Deux (%' ESCAPE '\');
UPDATE deals SET image = '/posters/jurassic-park.jpg' WHERE image IS NULL AND (title = 'Jurassic Park' OR title LIKE 'Jurassic Park (%' ESCAPE '\');
UPDATE deals SET image = '/posters/kingdom-of-the-planet-of-the-apes.jpg' WHERE image IS NULL AND (title = 'Kingdom of the Planet of the Apes' OR title LIKE 'Kingdom of the Planet of the Apes (%' ESCAPE '\');
UPDATE deals SET image = '/posters/klaus.jpg' WHERE image IS NULL AND (title = 'Klaus' OR title LIKE 'Klaus (%' ESCAPE '\');
UPDATE deals SET image = '/posters/knives-out.jpg' WHERE image IS NULL AND (title = 'Knives Out' OR title LIKE 'Knives Out (%' ESCAPE '\');
UPDATE deals SET image = '/posters/kung-fu-panda-4.jpg' WHERE image IS NULL AND (title = 'Kung Fu Panda 4' OR title LIKE 'Kung Fu Panda 4 (%' ESCAPE '\');
UPDATE deals SET image = '/posters/la-la-land.jpg' WHERE image IS NULL AND (title = 'La La Land' OR title LIKE 'La La Land (%' ESCAPE '\');
UPDATE deals SET image = '/posters/last-night-in-soho.jpg' WHERE image IS NULL AND (title = 'Last Night in Soho' OR title LIKE 'Last Night in Soho (%' ESCAPE '\');
UPDATE deals SET image = '/posters/l-on-the-professional.jpg' WHERE image IS NULL AND (title = 'Léon: The Professional' OR title LIKE 'Léon: The Professional (%' ESCAPE '\');
UPDATE deals SET image = '/posters/longlegs.jpg' WHERE image IS NULL AND (title = 'Longlegs' OR title LIKE 'Longlegs (%' ESCAPE '\');
UPDATE deals SET image = '/posters/luca.jpg' WHERE image IS NULL AND (title = 'Luca' OR title LIKE 'Luca (%' ESCAPE '\');
UPDATE deals SET image = '/posters/mad-max-fury-road.jpg' WHERE image IS NULL AND (title = 'Mad Max: Fury Road' OR title LIKE 'Mad Max: Fury Road (%' ESCAPE '\');
UPDATE deals SET image = '/posters/maestro.jpg' WHERE image IS NULL AND (title = 'Maestro' OR title LIKE 'Maestro (%' ESCAPE '\');
UPDATE deals SET image = '/posters/may-december.jpg' WHERE image IS NULL AND (title = 'May December' OR title LIKE 'May December (%' ESCAPE '\');
UPDATE deals SET image = '/posters/midsommar.jpg' WHERE image IS NULL AND (title = 'Midsommar' OR title LIKE 'Midsommar (%' ESCAPE '\');
UPDATE deals SET image = '/posters/migration.jpg' WHERE image IS NULL AND (title = 'Migration' OR title LIKE 'Migration (%' ESCAPE '\');
UPDATE deals SET image = '/posters/mission-impossible-dead-reckoning.jpg' WHERE image IS NULL AND (title = 'Mission: Impossible - Dead Reckoning' OR title LIKE 'Mission: Impossible - Dead Reckoning (%' ESCAPE '\');
UPDATE deals SET image = '/posters/moana-2.jpg' WHERE image IS NULL AND (title = 'Moana 2' OR title LIKE 'Moana 2 (%' ESCAPE '\');
UPDATE deals SET image = '/posters/napoleon.jpg' WHERE image IS NULL AND (title = 'Napoleon' OR title LIKE 'Napoleon (%' ESCAPE '\');
UPDATE deals SET image = '/posters/nightmare-alley.jpg' WHERE image IS NULL AND (title = 'Nightmare Alley' OR title LIKE 'Nightmare Alley (%' ESCAPE '\');
UPDATE deals SET image = '/posters/no-country-for-old-men.jpg' WHERE image IS NULL AND (title = 'No Country for Old Men' OR title LIKE 'No Country for Old Men (%' ESCAPE '\');
UPDATE deals SET image = '/posters/no-time-to-die.jpg' WHERE image IS NULL AND (title = 'No Time to Die' OR title LIKE 'No Time to Die (%' ESCAPE '\');
UPDATE deals SET image = '/posters/nomadland.jpg' WHERE image IS NULL AND (title = 'Nomadland' OR title LIKE 'Nomadland (%' ESCAPE '\');
UPDATE deals SET image = '/posters/nope.jpg' WHERE image IS NULL AND (title = 'Nope' OR title LIKE 'Nope (%' ESCAPE '\');
UPDATE deals SET image = '/posters/nosferatu.jpg' WHERE image IS NULL AND (title = 'Nosferatu' OR title LIKE 'Nosferatu (%' ESCAPE '\');
UPDATE deals SET image = '/posters/once-upon-a-time-in-hollywood.jpg' WHERE image IS NULL AND (title = 'Once Upon a Time in Hollywood' OR title LIKE 'Once Upon a Time in Hollywood (%' ESCAPE '\');
UPDATE deals SET image = '/posters/oppenheimer-imax-edition.jpg' WHERE image IS NULL AND (title = 'Oppenheimer: IMAX Edition' OR title LIKE 'Oppenheimer: IMAX Edition (%' ESCAPE '\');
UPDATE deals SET image = '/posters/parasite.jpg' WHERE image IS NULL AND (title = 'Parasite' OR title LIKE 'Parasite (%' ESCAPE '\');
UPDATE deals SET image = '/posters/past-lives.jpg' WHERE image IS NULL AND (title = 'Past Lives' OR title LIKE 'Past Lives (%' ESCAPE '\');
UPDATE deals SET image = '/posters/prey.jpg' WHERE image IS NULL AND (title = 'Prey' OR title LIKE 'Prey (%' ESCAPE '\');
UPDATE deals SET image = '/posters/princess-mononoke.jpg' WHERE image IS NULL AND (title = 'Princess Mononoke' OR title LIKE 'Princess Mononoke (%' ESCAPE '\');
UPDATE deals SET image = '/posters/priscilla.jpg' WHERE image IS NULL AND (title = 'Priscilla' OR title LIKE 'Priscilla (%' ESCAPE '\');
UPDATE deals SET image = '/posters/pulp-fiction.jpg' WHERE image IS NULL AND (title = 'Pulp Fiction' OR title LIKE 'Pulp Fiction (%' ESCAPE '\');
UPDATE deals SET image = '/posters/puss-in-boots.jpg' WHERE image IS NULL AND (title = 'Puss in Boots' OR title LIKE 'Puss in Boots (%' ESCAPE '\');
UPDATE deals SET image = '/posters/raiders-of-the-lost-ark.jpg' WHERE image IS NULL AND (title = 'Raiders of the Lost Ark' OR title LIKE 'Raiders of the Lost Ark (%' ESCAPE '\');
UPDATE deals SET image = '/posters/raya-and-the-last-dragon.jpg' WHERE image IS NULL AND (title = 'Raya and the Last Dragon' OR title LIKE 'Raya and the Last Dragon (%' ESCAPE '\');
UPDATE deals SET image = '/posters/rebel-moon.jpg' WHERE image IS NULL AND (title = 'Rebel Moon' OR title LIKE 'Rebel Moon (%' ESCAPE '\');
UPDATE deals SET image = '/posters/rrr.jpg' WHERE image IS NULL AND (title = 'RRR' OR title LIKE 'RRR (%' ESCAPE '\');
UPDATE deals SET image = '/posters/saltburn.jpg' WHERE image IS NULL AND (title = 'Saltburn' OR title LIKE 'Saltburn (%' ESCAPE '\');
UPDATE deals SET image = '/posters/saving-private-ryan.jpg' WHERE image IS NULL AND (title = 'Saving Private Ryan' OR title LIKE 'Saving Private Ryan (%' ESCAPE '\');
UPDATE deals SET image = '/posters/schindlers-list.jpg' WHERE image IS NULL AND (title = 'Schindler''s List' OR title LIKE 'Schindler''s List (%' ESCAPE '\');
UPDATE deals SET image = '/posters/shang-chi.jpg' WHERE image IS NULL AND (title = 'Shang-Chi' OR title LIKE 'Shang-Chi (%' ESCAPE '\');
UPDATE deals SET image = '/posters/sicario.jpg' WHERE image IS NULL AND (title = 'Sicario' OR title LIKE 'Sicario (%' ESCAPE '\');
UPDATE deals SET image = '/posters/smile.jpg' WHERE image IS NULL AND (title = 'Smile' OR title LIKE 'Smile (%' ESCAPE '\');
UPDATE deals SET image = '/posters/sonic-the-hedgehog-3.jpg' WHERE image IS NULL AND (title = 'Sonic the Hedgehog 3' OR title LIKE 'Sonic the Hedgehog 3 (%' ESCAPE '\');
UPDATE deals SET image = '/posters/soul.jpg' WHERE image IS NULL AND (title = 'Soul' OR title LIKE 'Soul (%' ESCAPE '\');
UPDATE deals SET image = '/posters/spider-man-into-the-spider-verse.jpg' WHERE image IS NULL AND (title = 'Spider-Man: Into the Spider-Verse' OR title LIKE 'Spider-Man: Into the Spider-Verse (%' ESCAPE '\');
UPDATE deals SET image = '/posters/spider-man-no-way-home.jpg' WHERE image IS NULL AND (title = 'Spider-Man: No Way Home' OR title LIKE 'Spider-Man: No Way Home (%' ESCAPE '\');
UPDATE deals SET image = '/posters/spirited-away.jpg' WHERE image IS NULL AND (title = 'Spirited Away' OR title LIKE 'Spirited Away (%' ESCAPE '\');
UPDATE deals SET image = '/posters/superbad.jpg' WHERE image IS NULL AND (title = 'Superbad' OR title LIKE 'Superbad (%' ESCAPE '\');
UPDATE deals SET image = '/posters/talk-to-me.jpg' WHERE image IS NULL AND (title = 'Talk to Me' OR title LIKE 'Talk to Me (%' ESCAPE '\');
UPDATE deals SET image = '/posters/t-r.jpg' WHERE image IS NULL AND (title = 'Tár' OR title LIKE 'Tár (%' ESCAPE '\');
UPDATE deals SET image = '/posters/tenet.jpg' WHERE image IS NULL AND (title = 'Tenet' OR title LIKE 'Tenet (%' ESCAPE '\');
UPDATE deals SET image = '/posters/terminator-2-judgment-day.jpg' WHERE image IS NULL AND (title = 'Terminator 2: Judgment Day' OR title LIKE 'Terminator 2: Judgment Day (%' ESCAPE '\');
UPDATE deals SET image = '/posters/the-banshees-of-inisherin.jpg' WHERE image IS NULL AND (title = 'The Banshees of Inisherin' OR title LIKE 'The Banshees of Inisherin (%' ESCAPE '\');
UPDATE deals SET image = '/posters/the-boy-and-the-heron.jpg' WHERE image IS NULL AND (title = 'The Boy and the Heron' OR title LIKE 'The Boy and the Heron (%' ESCAPE '\');
UPDATE deals SET image = '/posters/the-brutalist.jpg' WHERE image IS NULL AND (title = 'The Brutalist' OR title LIKE 'The Brutalist (%' ESCAPE '\');
UPDATE deals SET image = '/posters/the-conjuring.jpg' WHERE image IS NULL AND (title = 'The Conjuring' OR title LIKE 'The Conjuring (%' ESCAPE '\');
UPDATE deals SET image = '/posters/the-creator.jpg' WHERE image IS NULL AND (title = 'The Creator' OR title LIKE 'The Creator (%' ESCAPE '\');
UPDATE deals SET image = '/posters/the-dark-knight.jpg' WHERE image IS NULL AND (title = 'The Dark Knight' OR title LIKE 'The Dark Knight (%' ESCAPE '\');
UPDATE deals SET image = '/posters/the-departed.jpg' WHERE image IS NULL AND (title = 'The Departed' OR title LIKE 'The Departed (%' ESCAPE '\');
UPDATE deals SET image = '/posters/the-equalizer-3.jpg' WHERE image IS NULL AND (title = 'The Equalizer 3' OR title LIKE 'The Equalizer 3 (%' ESCAPE '\');
UPDATE deals SET image = '/posters/the-fabelmans.jpg' WHERE image IS NULL AND (title = 'The Fabelmans' OR title LIKE 'The Fabelmans (%' ESCAPE '\');
UPDATE deals SET image = '/posters/the-fall-guy.jpg' WHERE image IS NULL AND (title = 'The Fall Guy' OR title LIKE 'The Fall Guy (%' ESCAPE '\');
UPDATE deals SET image = '/posters/the-french-dispatch.jpg' WHERE image IS NULL AND (title = 'The French Dispatch' OR title LIKE 'The French Dispatch (%' ESCAPE '\');
UPDATE deals SET image = '/posters/the-godfather.jpg' WHERE image IS NULL AND (title = 'The Godfather' OR title LIKE 'The Godfather (%' ESCAPE '\');
UPDATE deals SET image = '/posters/the-grand-budapest-hotel.jpg' WHERE image IS NULL AND (title = 'The Grand Budapest Hotel' OR title LIKE 'The Grand Budapest Hotel (%' ESCAPE '\');
UPDATE deals SET image = '/posters/the-iron-claw.jpg' WHERE image IS NULL AND (title = 'The Iron Claw' OR title LIKE 'The Iron Claw (%' ESCAPE '\');
UPDATE deals SET image = '/posters/the-killer.jpg' WHERE image IS NULL AND (title = 'The Killer' OR title LIKE 'The Killer (%' ESCAPE '\');
UPDATE deals SET image = '/posters/the-lighthouse.jpg' WHERE image IS NULL AND (title = 'The Lighthouse' OR title LIKE 'The Lighthouse (%' ESCAPE '\');
UPDATE deals SET image = '/posters/the-lord-of-the-rings-the-fellowship-of-the-ring.jpg' WHERE image IS NULL AND (title = 'The Lord of the Rings: The Fellowship of the Ring' OR title LIKE 'The Lord of the Rings: The Fellowship of the Ring (%' ESCAPE '\');
UPDATE deals SET image = '/posters/the-martian.jpg' WHERE image IS NULL AND (title = 'The Martian' OR title LIKE 'The Martian (%' ESCAPE '\');
UPDATE deals SET image = '/posters/the-marvels.jpg' WHERE image IS NULL AND (title = 'The Marvels' OR title LIKE 'The Marvels (%' ESCAPE '\');
UPDATE deals SET image = '/posters/the-matrix.jpg' WHERE image IS NULL AND (title = 'The Matrix' OR title LIKE 'The Matrix (%' ESCAPE '\');
UPDATE deals SET image = '/posters/the-nice-guys.jpg' WHERE image IS NULL AND (title = 'The Nice Guys' OR title LIKE 'The Nice Guys (%' ESCAPE '\');
UPDATE deals SET image = '/posters/the-northman.jpg' WHERE image IS NULL AND (title = 'The Northman' OR title LIKE 'The Northman (%' ESCAPE '\');
UPDATE deals SET image = '/posters/the-power-of-the-dog.jpg' WHERE image IS NULL AND (title = 'The Power of the Dog' OR title LIKE 'The Power of the Dog (%' ESCAPE '\');
UPDATE deals SET image = '/posters/the-return-of-the-king.jpg' WHERE image IS NULL AND (title = 'The Return of the King' OR title LIKE 'The Return of the King (%' ESCAPE '\');
UPDATE deals SET image = '/posters/the-revenant.jpg' WHERE image IS NULL AND (title = 'The Revenant' OR title LIKE 'The Revenant (%' ESCAPE '\');
UPDATE deals SET image = '/posters/the-shawshank-redemption.jpg' WHERE image IS NULL AND (title = 'The Shawshank Redemption' OR title LIKE 'The Shawshank Redemption (%' ESCAPE '\');
UPDATE deals SET image = '/posters/the-shining.jpg' WHERE image IS NULL AND (title = 'The Shining' OR title LIKE 'The Shining (%' ESCAPE '\');
UPDATE deals SET image = '/posters/the-substance.jpg' WHERE image IS NULL AND (title = 'The Substance' OR title LIKE 'The Substance (%' ESCAPE '\');
UPDATE deals SET image = '/posters/the-suicide-squad.jpg' WHERE image IS NULL AND (title = 'The Suicide Squad' OR title LIKE 'The Suicide Squad (%' ESCAPE '\');
UPDATE deals SET image = '/posters/the-thing.jpg' WHERE image IS NULL AND (title = 'The Thing' OR title LIKE 'The Thing (%' ESCAPE '\');
UPDATE deals SET image = '/posters/the-two-towers.jpg' WHERE image IS NULL AND (title = 'The Two Towers' OR title LIKE 'The Two Towers (%' ESCAPE '\');
UPDATE deals SET image = '/posters/the-whale.jpg' WHERE image IS NULL AND (title = 'The Whale' OR title LIKE 'The Whale (%' ESCAPE '\');
UPDATE deals SET image = '/posters/the-wild-robot.jpg' WHERE image IS NULL AND (title = 'The Wild Robot' OR title LIKE 'The Wild Robot (%' ESCAPE '\');
UPDATE deals SET image = '/posters/the-witch.jpg' WHERE image IS NULL AND (title = 'The Witch' OR title LIKE 'The Witch (%' ESCAPE '\');
UPDATE deals SET image = '/posters/the-zone-of-interest.jpg' WHERE image IS NULL AND (title = 'The Zone of Interest' OR title LIKE 'The Zone of Interest (%' ESCAPE '\');
UPDATE deals SET image = '/posters/there-will-be-blood.jpg' WHERE image IS NULL AND (title = 'There Will Be Blood' OR title LIKE 'There Will Be Blood (%' ESCAPE '\');
UPDATE deals SET image = '/posters/top-gun-maverick.jpg' WHERE image IS NULL AND (title = 'Top Gun: Maverick' OR title LIKE 'Top Gun: Maverick (%' ESCAPE '\');
UPDATE deals SET image = '/posters/toy-story.jpg' WHERE image IS NULL AND (title = 'Toy Story' OR title LIKE 'Toy Story (%' ESCAPE '\');
UPDATE deals SET image = '/posters/triangle-of-sadness.jpg' WHERE image IS NULL AND (title = 'Triangle of Sadness' OR title LIKE 'Triangle of Sadness (%' ESCAPE '\');
UPDATE deals SET image = '/posters/turning-red.jpg' WHERE image IS NULL AND (title = 'Turning Red' OR title LIKE 'Turning Red (%' ESCAPE '\');
UPDATE deals SET image = '/posters/twisters.jpg' WHERE image IS NULL AND (title = 'Twisters' OR title LIKE 'Twisters (%' ESCAPE '\');
UPDATE deals SET image = '/posters/up.jpg' WHERE image IS NULL AND (title = 'Up' OR title LIKE 'Up (%' ESCAPE '\');
UPDATE deals SET image = '/posters/us.jpg' WHERE image IS NULL AND (title = 'Us' OR title LIKE 'Us (%' ESCAPE '\');
UPDATE deals SET image = '/posters/wall-e.jpg' WHERE image IS NULL AND (title = 'WALL-E' OR title LIKE 'WALL-E (%' ESCAPE '\');
UPDATE deals SET image = '/posters/west-side-story.jpg' WHERE image IS NULL AND (title = 'West Side Story' OR title LIKE 'West Side Story (%' ESCAPE '\');
UPDATE deals SET image = '/posters/whiplash.jpg' WHERE image IS NULL AND (title = 'Whiplash' OR title LIKE 'Whiplash (%' ESCAPE '\');
UPDATE deals SET image = '/posters/wicked.jpg' WHERE image IS NULL AND (title = 'Wicked' OR title LIKE 'Wicked (%' ESCAPE '\');
UPDATE deals SET image = '/posters/wonka.jpg' WHERE image IS NULL AND (title = 'Wonka' OR title LIKE 'Wonka (%' ESCAPE '\');
UPDATE deals SET image = '/posters/your-name.jpg' WHERE image IS NULL AND (title = 'Your Name' OR title LIKE 'Your Name (%' ESCAPE '\');
